version: "3.9"

services:
  web:
    build:
      context: ../
      dockerfile: /docker/Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # Inside Docker, connect to Mongo via the service name "mongodb"
      MONGODB_URI: ${MONGODB_URI:-mongodb://mongodb:27017/mydb}
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb-data: